export const ON_FETCH_GIPHS_SUCCESS = 'ON_FETCH_GIPHS_SUCCESS';
export const ON_FETCH_FAILURE = 'ON_FETCH_FAILURE';
export const SORT_BY_VALUE_CHANGE = 'SORT_BY_VALUE_CHANGE';
export const FETCH_DATA_BEGIN = 'FETCH_DATA_BEGIN';
export const ON_START_FETCH_GIPHS = 'ON_START_FETCH_GIPHS';
export const APP_INIT = 'APP_INIT';