export const ON_FETCH_GIPHS_SUCCESS = 'ON_FETCH_GIPHS_SUCCESS';
export const ON_FETCH_FAILURE = 'ON_FETCH_FAILURE';
export const FETCH_DATA_BEGIN = 'FETCH_DATA_BEGIN';
export const ON_START_FETCH_GIPHS = 'ON_START_FETCH_GIPHS';
export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';