export const PRODUCT_ADD = 'PRODUCT_ADD';
export const PRODUCT_RECEIVED = 'PRODUCT_RECEIVED';
export const FETCH_CURRENCY_DATA_BEGIN = 'FETCH_CURRENCY_DATA_BEGIN';
export const FETCH_CURRENCY_RATES_SUCCESS = 'FETCH_CURRENCY_RATES_SUCCESS';
export const FETCH_CURRENCY_RATES_FAILURE = 'FETCH_CURRENCY_RATES_FAILURE';